### ISSUE TITLE
create endpoints for new node registration

### ISSUE THREAD

**Issue by vivekrj0** [vivekrj0/AutoChain#1]
If we change the port number from 5000 to 5001 and run another instance of autochain.py. Then in a POST request on your old node, there is the registration of your new node. Create this new endpoint for the registration :
```bash
/nodes/register
```
add some transactions in the new node and create another endpoint 
```bash
/nodes/resolve
```
for merging the conflicts created by the two nodes.

**Comment by PrabhuKGP** [comment]
@vivekrj0 I'm working on this issue

**Comment by vivekrj0** [comment]
#5
